import Provider from "../context/Provider";
import "@/app/global.css";

export const metadata = {
  title: "Guessing Songs",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider>
      <html lang="en">
        <body style={{ backgroundColor: "black" }}>{children}</body>
      </html>
    </Provider>
  );
}
